name: Deploy Python Function to Azure

on:
  push:
    branches:
      - master
    paths:
      - 'funcx-v7/**'

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'funcx-v7'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Create deployment package'
        run: |
          pushd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../deployment.zip .
          popd

      - name: 'Deploy to Azure Function App'
        uses: Azure/functions-action@v1
        with:
          app-name: func701
          package: 'deployment.zip'