
name: Deploy Python Function to Azure

on:
  push:
    branches:
      - master
    paths:
      - 'funcx-v7/**'

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'funcx-v7'  # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.10'                    # set this to the python version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Set up Python version'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: 'Deploy to Azure Function App'
        uses: Azure/functions-action@v1
        with:
          app-name: func701 # <--ACTION REQUIRED
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # <--ACTION REQUIRED
