name: Build and deploy #14 Python project to Azure Function App - proc-function7

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 'Install dependencies'
        run: |
          pip install --target=".python_packages/lib/site-packages" -r requirements.txt
        working-directory: './funcX-v6'

      - name: 'Zip folder for deployment'
        run: zip -r release.zip .
        working-directory: './funcX-v6'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: './funcX-v6/release.zip'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: 'Deploy to Azure Functions with Azure CLI'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az functionapp deployment source config-zip --resource-group <tu-resource-group> --name proc-function7 --src release.zip
        env:
          AZURE_FUNCTIONS_PUBLISH_PROFILE: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7E1ACEA18B19491CA751E8970D92748E }}
