name: Build and deploy Node.js app to Azure Web App - get2-invoices-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: './get-invoices-backend' # <--- Add this line!
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: './get-invoices-backend' # <--- Update this path to the correct directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'get2-invoices-backend'
          slot-name: 'Production'
          package: '.' # The package is now the downloaded artifact, which is the contents of the backend folder.
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CDBC1C2B8EBC44CCBD4F46AB0E6AAA2E }}
